const $=id=>document.getElementById(id);const start=$('start'),speed=$('speed'),status=$('status'),progress=$('progress'),ping=$('ping'),download=$('download'),upload=$('upload'),network=$('network'),connection=$('connection'),gauge=document.querySelector('.gauge');
const CLOUDFLARE='https://speed.cloudflare.com/__down?bytes=';
function setSpeed(v){const n=Math.max(0,Number(v)||0);speed.textContent=n.toFixed(n<10?1:0);gauge.style.setProperty('--deg',`${Math.min(360,n/500*360)}deg`)}
async function latency(){let best=Infinity;for(let i=0;i<3;i++){const t=performance.now();try{await fetch('https://speed.cloudflare.com/__down?bytes=0&cache='+Math.random(),{cache:'no-store'});best=Math.min(best,performance.now()-t)}catch{}}return Number.isFinite(best)?Math.round(best):null}
async function downloadTest(){const sizes=[100000,500000,1000000,5000000];let bytes=0,started=performance.now();for(let i=0;i<sizes.length;i++){const t=performance.now();try{const r=await fetch(CLOUDFLARE+sizes[i]+'&cache='+Math.random(),{cache:'no-store'});const b=await r.arrayBuffer();bytes+=b.byteLength;const elapsed=(performance.now()-t)/1000;const mbps=b.byteLength*8/elapsed/1e6;setSpeed(mbps);progress.style.width=`${25+(i+1)*14}%`}catch{}}const sec=(performance.now()-started)/1000;return bytes?bytes*8/sec/1e6:null}
async function uploadTest(){const sizes=[250000,750000,1500000];let bytes=0,started=performance.now();for(let i=0;i<sizes.length;i++){const data=new Uint8Array(sizes[i]);crypto.getRandomValues(data.subarray(0,Math.min(65536,data.length)));const t=performance.now();try{const r=await fetch('https://speed.cloudflare.com/__up?cache='+Math.random(),{method:'POST',body:data,cache:'no-store'});if(r.ok)bytes+=data.length;const sec=(performance.now()-t)/1000;setSpeed(data.length*8/sec/1e6);progress.style.width=`${70+(i+1)*9}%`}catch{}}const sec=(performance.now()-started)/1000;return bytes?bytes*8/sec/1e6:null}
function detect(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;if(c){connection.textContent=c.effectiveType?`${c.effectiveType.toUpperCase()} · ${c.downlink||'?'} Mbps`:'Available'}else connection.textContent='Browser API unavailable';network.textContent=navigator.onLine?'Online':'Offline'}
start.onclick=async()=>{if(!navigator.onLine){status.textContent='No internet connection';return}start.disabled=true;ping.textContent='…';download.textContent='…';upload.textContent='…';progress.style.width='4%';setSpeed(0);status.textContent='Measuring latency…';const p=await latency();ping.textContent=p??'—';status.textContent='Testing download…';const d=await downloadTest();download.textContent=d?d.toFixed(1):'—';status.textContent='Testing upload…';const u=await uploadTest();upload.textContent=u?u.toFixed(1):'—';const best=Math.max(d||0,u||0);setSpeed(best);progress.style.width='100%';status.textContent='Test complete';start.disabled=false};
$('theme').onclick=()=>document.documentElement.classList.toggle('light');detect();
