const $=id=>document.getElementById(id);
const start=$('start'),speed=$('speed'),status=$('status'),progress=$('progress'),ping=$('ping'),download=$('download'),upload=$('upload'),network=$('network'),gauge=document.querySelector('.gauge');
const DOWN='https://speed.cloudflare.com/__down?bytes=';const UP='https://speed.cloudflare.com/__up?cache=';
function setSpeed(v){const n=Math.max(0,Number(v)||0);speed.textContent=n.toFixed(n<10?1:0);gauge.style.setProperty('--deg',`${Math.min(360,n/1000*360)}deg`)}
function rand(){return Math.random().toString(36).slice(2)}
async function latency(){const s=[];for(let i=0;i<5;i++){const t=performance.now();try{const r=await fetch(DOWN+'1&cache='+rand(),{cache:'no-store'});if(r.ok)s.push(performance.now()-t)}catch{}}if(!s.length)return null;s.sort((a,b)=>a-b);return Math.round(s[Math.floor(s.length/2)])}
async function downloadTest(){const size=10000000,workers=3,end=performance.now()+6500;let total=0;const run=async()=>{while(performance.now()<end){const t=performance.now();try{const r=await fetch(DOWN+size+'&cache='+rand(),{cache:'no-store'});const b=await r.arrayBuffer();const sec=(performance.now()-t)/1000;total+=b.byteLength;const instant=b.byteLength*8/sec/1e6;if(instant>0)setSpeed(instant)}catch{break}}};await Promise.all(Array.from({length:workers},run));return total?total*8/6.5/1e6:null}
async function uploadTest(){const size=2000000,payload=new Uint8Array(size),workers=2,duration=5500,started=performance.now();let total=0;const run=async()=>{while(performance.now()-started<duration){try{const t=performance.now();const r=await fetch(UP+rand(),{method:'POST',body:payload,cache:'no-store',keepalive:false});if(r.ok){const sec=(performance.now()-t)/1000;total+=size;const instant=size*8/sec/1e6;if(instant>0)setSpeed(instant)}}catch{break}}};await Promise.all(Array.from({length:workers},run));return total?total*8/((performance.now()-started)/1000)/1e6:null}
function browserName(){const ua=navigator.userAgent;if(/Edg\//.test(ua))return'Microsoft Edge';if(/Chrome\//.test(ua)&&!/Edg\//.test(ua))return'Google Chrome';if(/Firefox\//.test(ua))return'Mozilla Firefox';if(/Safari\//.test(ua)&&!/Chrome\//.test(ua))return'Safari';return'Unknown'}
function deviceName(){const ua=navigator.userAgent;if(/Android/i.test(ua))return'Android';if(/iPhone|iPad|iPod/i.test(ua))return'iOS';if(/Windows/i.test(ua))return'Windows';if(/Mac OS/i.test(ua))return'macOS';if(/Linux/i.test(ua))return'Linux';return'Unknown'}
function transport(){try{const entries=performance.getEntriesByType('resource');const e=entries.find(x=>x.name.startsWith('https://speed.cloudflare.com'));return e?.nextHopProtocol||'Not exposed'}catch{return'Not exposed'}}
function detectNetwork(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;const typeMap={wifi:'Wi‑Fi',cellular:'Mobile data',ethernet:'Ethernet',bluetooth:'Bluetooth',none:'Offline',wimax:'WiMAX',other:'Other',unknown:'Unknown'};network.textContent=c?.type?typeMap[c.type]||c.type:'Not exposed by browser';$('effective').textContent=c?.effectiveType?c.effectiveType.toUpperCase():'Not exposed';$('downlink').textContent=typeof c?.downlink==='number'?`${c.downlink} Mbps`:'Not exposed';$('downlinkMax').textContent=typeof c?.downlinkMax==='number'&&isFinite(c.downlinkMax)?`${c.downlinkMax} Mbps`:'Not exposed';$('browserRtt').textContent=typeof c?.rtt==='number'?`${c.rtt} ms`:'Not exposed';$('saveData').textContent=typeof c?.saveData==='boolean'?(c.saveData?'On':'Off'):'Not exposed';$('online').textContent=navigator.onLine?'Online':'Offline';$('device').textContent=deviceName();$('browser').textContent=browserName();$('transport').textContent=transport();$('secure').textContent=location.protocol==='https:'?'HTTPS':'HTTP';}
start.onclick=async()=>{if(!navigator.onLine){status.textContent='No internet connection';return}start.disabled=true;ping.textContent='…';download.textContent='…';upload.textContent='…';progress.style.width='3%';setSpeed(0);status.textContent='Finding latency…';const p=await latency();ping.textContent=p??'—';progress.style.width='18%';status.textContent='Measuring download…';const d=await downloadTest();download.textContent=d?d.toFixed(1):'—';progress.style.width='62%';status.textContent='Measuring upload…';const u=await uploadTest();upload.textContent=u?u.toFixed(1):'—';progress.style.width='100%';setSpeed(Math.max(d||0,u||0));status.textContent='Test complete';detectNetwork();start.disabled=false};
$('theme').onclick=()=>document.documentElement.classList.toggle('light');
['change','online','offline'].forEach(ev=>{const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;if(c?.addEventListener&&ev==='change')c.addEventListener(ev,detectNetwork);else window.addEventListener(ev,detectNetwork)});detectNetwork();
